"use client";

import { motion } from "framer-motion";
import { Code2, Gauge, Terminal, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";

const TrustSection = () => {
  return (
    <section id="trust" className="py-32 px-6 bg-muted/5">
      <div className="container mx-auto max-w-6xl flex flex-col lg:flex-row items-center gap-20">
        {/* LEFT COLUMN */}
        <div className="flex-1">
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-8"
          >
            <Badge className="px-4 py-1 text-[10px] font-black uppercase tracking-[0.2em] rounded-full bg-accent/10 border border-accent/20 text-accent">
              Explainability Engine
            </Badge>
          </motion.div>

          <h2 className="text-4xl md:text-5xl font-black mb-8 tracking-tight">
            AI you can audit.
          </h2>

          <p className="text-lg text-muted-foreground mb-12 max-w-lg leading-relaxed">
            Eliminate the "Black Box" problem. Every insight generated by ExcelGPT
            is accompanied by a full logic trace and the exact Python code used.
          </p>

          <div className="space-y-10">
            <motion.div whileHover={{ x: 10 }} className="flex gap-6 group">
              <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center text-primary shrink-0 border border-primary/20 group-hover:shadow-[0_0_15px_var(--primary)] transition-shadow duration-300">
                <Code2 size={24} />
              </div>
              <div>
                <h4 className="font-bold text-xl mb-2">Code Verification</h4>
                <p className="text-sm text-muted-foreground">
                  Instantly review the source logic. No hidden prompt magic or
                  unexplained numbers.
                </p>
              </div>
            </motion.div>

            <motion.div whileHover={{ x: 10 }} className="flex gap-6 group">
              <div className="w-14 h-14 rounded-2xl bg-accent/10 flex items-center justify-center text-accent shrink-0 border border-accent/20 group-hover:shadow-[0_0_15px_var(--accent)] transition-shadow duration-300">
                <Gauge size={24} />
              </div>
              <div>
                <h4 className="font-bold text-xl mb-2">Confidence Scores</h4>
                <p className="text-sm text-muted-foreground">
                  Get probabilistic certainty levels for every deduction made by
                  the local model.
                </p>
              </div>
            </motion.div>
          </div>
        </div>

        {/* RIGHT COLUMN */}
        <div className="flex-1 w-full max-w-xl">
          <motion.div
            layout
            initial={{ opacity: 0, x: 50 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
          >
            <Card className="p-10 rounded-[3rem] glass-card shadow-2xl relative border border-border bg-card/50">
              <div className="flex justify-between items-center mb-10">
                <div className="flex items-center gap-3">
                  <div className="w-2 h-2 rounded-full bg-accent animate-pulse" />
                  <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">
                    Local Reasoning Trace
                  </span>
                </div>

                <Badge
                  variant="outline"
                  className="px-4 py-1.5 text-[10px] font-black uppercase rounded-xl bg-accent/10 border border-accent/20 text-accent"
                >
                  Confidence: 99.1%
                </Badge>
              </div>

              <div className="space-y-4 mb-10">
                <p className="text-xl font-medium tracking-tight leading-relaxed">
                  "Based on <span className="text-accent">Dataset_A</span>, the
                  projected churn for <span className="text-accent">Q4</span>{" "}
                  will decrease by{" "}
                  <span className="text-accent font-black">12.4%</span>."
                </p>

                <div className="flex items-center gap-2 text-[10px] font-mono text-muted-foreground">
                  <Search size={12} />
                  <span>Citing rows 452 - 1,209</span>
                </div>
              </div>

              {/* CODE BLOCK */}
              <Card className="bg-muted rounded-3xl p-8 font-mono text-xs text-muted-foreground border border-border overflow-hidden shadow-inner">
                <div className="flex items-center gap-2 mb-4 opacity-50">
                  <Terminal size={14} />
                  <span className="tracking-widest uppercase text-[10px]">
                    local_execution.py
                  </span>
                </div>

                <Separator className="mb-4 opacity-50" />

                <ScrollArea className="h-40">
                  <div className="space-y-2 opacity-90 pr-4">
                    <p>
                      <span className="text-accent">import</span> pandas{" "}
                      <span className="text-accent">as</span> pd
                    </p>
                    <p>
                      df = pd.read_csv(
                      <span className="text-primary">'local_memory.csv'</span>)
                    </p>
                    <p>
                      df[
                      <span className="text-primary">'Date'</span>] =
                      pd.to_datetime(df[
                      <span className="text-primary">'Date'</span>])
                    </p>
                    <p>
                      result = df.query(
                      <span className="text-primary">'Q == 4'</span>).churn.mean()
                    </p>
                    <p>
                      <span className="text-accent">print</span>(f
                      <span className="text-primary">
                        "Projected: {"{result}"}"
                      </span>
                      )
                    </p>
                  </div>
                </ScrollArea>
              </Card>
            </Card>
          </motion.div>
        </div>
      </div>
    </section>
  );
};

export default TrustSection;
